### ISSUE TITLE
Character links with accented characters are not working

### ISSUE THREAD

**Issue by Galarzaa90** [NabDev/NabBot#123]
When you click on the link of a character, like **Himmelhüpferin**, the link doesn't do anything.
![image](https://user-images.githubusercontent.com/12865379/44613242-c3318b00-a7c5-11e8-8583-63ed39142334.png)

**Comment by Tschis** [comment]
Just pasting the link `https://www.tibia.com/community/?subtopic=characters&name=Himmelh%FCpferin` in a message will show both the URL and the embed information. The link works on the embed but not on the message itself.

This indicates to me that: 
1. it could be a bug with Discord itself;
1. there is a way to make the embed link work, somehow;

**Comment by Galarzaa90** [comment]
And the bug can't be reproduced in Android, so it's definitely a Discord problem.

I'll see if there's a workaround. Otherwise I will just close it because it's not a NabBot bug 🤔.

**Comment by Tschis** [comment]
@Galarzaa90 I suggest new label: `bug-dependency` to indicate this is not related to NabBot.
The current `bug` label even states it is for problems directly related.

**Comment by Galarzaa90** [comment]
I even thing this should be labeled as not a bug and be closed as I don't think there's something that can be done. 🤔

**Comment by Tschis** [comment]
Sure, I agree. Although there might be a workaround (https://github.com/NabDev/NabBot/issues/123#issuecomment-416033415).

I just mean there should be a better label anyway.

**Comment by Galarzaa90** [comment]
I'm closing this since this is definitely a client bug. It only happens on desktop, I just noticed the `href` element doesn't even get set:

![image](https://user-images.githubusercontent.com/12865379/55765530-1559b080-5a25-11e9-99bd-e79f19b51b06.png)

And it doesn't happen on mobile.
