### ISSUE TITLE
addchar error

### ISSUE THREAD

**Issue by Legarius** [NabDev/NabBot#160]
## Platform information
- **Operating system:** 
Windows
- **Python version:**
Last
- **NabBot version:**
Last

## Bug information
When i try to addchar the system return aways can't find the user with xxxxxxxxxxxxxxx

**Comment by Galarzaa90** [comment]
What's the exact command input you're using?

**Comment by Galarzaa90** [comment]
So you are sure the user exists and is in your server?

Could you provide  some screenshots?

**Comment by Legarius** [comment]
Yes, i'm sure. I try with different users too

[https://imgur.com/a/yIErCON](url)

**Comment by Galarzaa90** [comment]
I think I found the issue, it's the space between the user name and the character's name.

I will fix it in a bit, but that should work for now.
Thanks for your report 😀

**Comment by Legarius** [comment]
You are welcome 

;) nice Work dude!!!
