### ISSUE TITLE
Calling /highscores with inexistent world gives "wrong category" message.

### ISSUE THREAD

**Issue by Tschis** [NabDev/NabBot#163]
For example, `/highscores fidera` gives `Invalid category, valid categories are: achievements, axe, club, distance, experience, fishing, fist, loyalty, magic, shielding and sword`.

I think this message can be improved because the user might not have tried to input a category and, therefore, the message might be confusing.

For example `Fidera` was a valid world in the past, or user could have a typo like `atica` instead of `Antica`.

An idea would be to use current category error message only if world is used and valid, i.e. `/highscores antica, sowrd` could return it.

**Comment by Galarzaa90** [comment]
But how do you know if it was an invalid world or an invalid category?

**Comment by Tschis** [comment]
If we can't tell, we should use a general message.
If we know it is a valid world, then we can show the invalid category message.

**Comment by Galarzaa90** [comment]
I agree, the message should be more general.
