### ISSUE TITLE
Fetch a list of (un)registered players to the Discord server (optionally: of a given guild)

### ISSUE THREAD

**Issue by dmngrsk** [NabDev/NabBot#96]
My suggestion is to add the following two commands:

- `/registered [guild_name]`
- `/unregistered guild_name`

I believe that would make tracking guild members much easier for leaders, especially to moderate people that do not bring anything to the community.

**Comment by Galarzaa90** [comment]
In the development version, I added a subcommand, `/unregistered guild` that shows you a list of guild members that are not registered or their owners are not in the current discord server.
